name: publish-images
on:
  release:
    types: [published]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.express
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/express-api:latest
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.streamlit
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/streamlit-ui:latest
